//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDI.Data.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Validation;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using EFDI.CommonLibrary.Models.Base;
    using EFDI.Data.Extensions;
    using EFDI.Data.Interfaces;
    using EFDI.Data.Models;
    
    public partial class EFDIDatabaseContainer : DbContext, IDbContext
    {
        public EFDIDatabaseContainer()
            : base("name=EFDIDatabaseContainer")
        {
        }
    
    	//------------------------------------------------------------------------------
    	// <auto-generated>
    	//    This code was generated from a template.
    	//
    	//    Customized - Added Constructor that takes connection string as parameter
    	// </auto-generated>
    	//------------------------------------------------------------------------------
    	public EFDIDatabaseContainer(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<BlogSubscription> BlogSubscriptions { get; set; }
    
    	//------------------------------------------------------------------------------
    	// <auto-generated>
    	//    This code was generated from a template.
    	//
    	//    Customized - Added code below.
    	// </auto-generated>
    	//------------------------------------------------------------------------------
    	public new DbSet<TPersistenceModel> Set<TPersistenceModel>() where TPersistenceModel : PersistenceModelBase
    	{
    		return base.Set<TPersistenceModel>();
    	}
    
    	public override int SaveChanges()
    	{
    		try
            {
                this.ApplyStateChanges();
                return base.SaveChanges();
            }
            catch (DbEntityValidationException exception)
            {
                var errorMessages = exception.EntityValidationErrors
    				.SelectMany(result => result.ValidationErrors)
    				.Select(result => result.ErrorMessage);
    
                var fullErrorMessage = string.Join("; ", errorMessages);
    			var exceptionMessage = string.Concat(exception.Message, " The validation errors are: ", fullErrorMessage);
    
                throw new DbEntityValidationException(exceptionMessage, exception.EntityValidationErrors);
            }
    	}
    }
}
