//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDI.Data.Models
{
    using EFDI.CommonLibrary.Models.Base;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class BlogSubscription : PersistenceModelBase
    {
        public long BlogSubscritionID { get; set; }
        public Nullable<System.Guid> UserProfileID { get; set; }
        [Key]
        public string EmailAddress { get; set; }
        public string Subscribefrom { get; set; }
        public System.DateTime CreatedDttm { get; set; }
        public System.DateTime ModifiedDttm { get; set; }
    }
}
